version: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "80:8080"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --quiet
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata: