version: '3'

services:
  nest:
    container_name: nest
    restart: always
    build: .
    ports:
      - "80:8080"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata: